export const btnData = [
    { data: "7", type: "primary", fn: "handleNumClick" },
    { data: "8", type: "primary", fn: "handleNumClick" },
    { data: "9", type: "primary", fn: "handleNumClick" },
    { data: "DEL", type: "special", fn: "handleDelClick" },
    { data: "4", type: "primary", fn: "handleNumClick" },
    { data: "5", type: "primary", fn: "handleNumClick" },
    { data: "6", type: "primary", fn: "handleNumClick" },
    { data: "+", type: "primary", fn: "handleNumClick" },
    { data: "1", type: "primary", fn: "handleNumClick" },
    { data: "2", type: "primary", fn: "handleNumClick" },
    { data: "3", type: "primary", fn: "handleNumClick" },
    { data: "-", type: "primary", fn: "handleNumClick" },
    { data: ".", type: "primary", fn: "handleNumClick" },
    { data: "0", type: "primary", fn: "handleNumClick" },
    { data: "/", type: "primary", fn: "handleNumClick" },
    { data: "*", type: "primary", fn: "handleNumClick" },
    { data: "RESET", type: "secondary", fn: "reset" },
    { data: "=", type: "tertiary", fn: "handleResultClick" },
  ];